language: groovy
rvm:
- 1.8.8
install:
- gradle build
before_script:
- gradle test
- export PLUGIN_VERSION=${TRAVIS_COMMIT:0:7}
script:
- gradle -PpluginVersion=${PLUGIN_VERSION}
jdk:
- oraclejdk9
deploy:
  provider: releases
  api_key:
    secure: C6ekkINK2db0elQ6nKc6QjER5ipu2aTY5PJsX50B/cOXfHsJ/CqNsRDliCeWIiL/fu46hGlvgGaBfFGDFQ9v3SBgsc4u/2zfHSmt0MtrnkfqpXz4zqokbMdJW3OGxb74wOuWkx4iU5z2mYGRfKSBUYnE5pxZhdG/+3MRhPYKUNUlZzNyOS65M6lHHUgvayR13ITDBXVkSz8UlGGNBWxYyi/jRYrS/jEdnDgAtSXlgxy9Y0oFhYmh5OICDRkc3popO8La84o3H79FJwyFrnFKhVYBsHTlT6nfQVoMGHV6J7cmW+tI2hqlS2IZY13Pn5X8e/QwhtodAY61gxC88DPB9SPeD2QQo8+rvAyictk5smgeYnZKerjywSb3lRBkN3Tne0PK5ZgckaEjZiAtVhwbIwdP2P8xfuNRHl+vUPi2GQ88ZTQCpQY9NQ1slLhp2F0Jd827seKROZn5rGhgfAwx3T0OF5XBBgecQQ7t/X8bUoMBZkjGCNht5DzDnxx8Se8rJRoYN58iDxwgkFmN42kULdkq97oCsNxL/p9rhfimvRO/8fVMudM4LyLeDcecOn4FDEjSeFn5/LU3jHLK2WwVqNaiU4T9+OA6hJ9UE3nsCzUg/YUZkh/yT0PFtSZLmoiq0vs14MkQBGPw1mfnB0JqfTPRO1e/fuKtOz+H2+ISoUE=
  file: /*.zip
  skip_cleanup: true
  on:
    tags: true
