language: groovy
rvm:
- 1.8.8
install:
- gradle build
before_script:
- gradle test
- export PLUGIN_VERSION=${TRAVIS_COMMIT:0:7}
script:
- gradle -PpluginVersion=${PLUGIN_VERSION}
jdk:
- oraclejdk9
deploy:
  provider: releases
  api_key:
    secure: EaLoBomZ9lW3nYYxzg6oHU7yXHKgoOWhaNLNkwUYv1jzfrAk9Bid3thoXDfSwzbo8+b1zSr19ZRmWB9pqf0XkP4khszMl9IOsCjYjPK1BrEJ5yDywRH29vh20/Uk7rTZ/kyHWrJ32JFb+MB9zmVElQ3HOoFpKwR80lAs7p8CdZ6qK2PsVhfAE3FiP7xEtWRlzqViRqOLNuslQS4erPkKsPWo4etf12nCg50GWccx1ZhP/oa58YhgVAt62nahoEwJXUPGRicgOR2TYhdfrmCRflXTjmGOCPIKkNewF/8ykXZlW0U9jTi7Cu0xZA/XseGyjQqNEd9kFll+xHDNHE1QoA6yXZh3ltCA4ZkA+XSa6nbv7u7wNi2xtbp1l34EtULcJJTgmptlIczFfM/qIyDdC8WTLU8OAOZ5UAXsjRA5+Y/tCoNh+MFu+MH6M7fJVeGV/kf9hiOzJX1PExPUeSt3pciQr+9oVBiBLexiZwk0SEupEYwImWj0xpj6zfAbdopoBd/1ouyg6tTBeQnul/lexyNk2pw69SiNMA9wrMtS9e/xvnsynSO9/F7OCozcu/AwgSZDjdVbMEiR0WFnhgv14TEaYsmYY84yChwvMjIFzgWgUD0yURdWDpz2RDNlAeoPVL2LdLq88hb5ZzQaJ9BR7oQkH3uVaEf3T5rR4p8y3Is=
  file: /*.zip
  skip_cleanup: true
  on:
    tags: true
